### ISSUE TITLE
Request to add a new forked library "Adafruit ADXL345 fork"

### ISSUE THREAD

**Issue by trycoon** [platformio/platformio-libmirror#103]
Since the Adafruit library contains more or less severe flaws, but still they seems unwilling to take Pull Requests, I made a fork including all PR and fixed all issues. Could you please consider including this in the platformio-library, it would make it soo much easier just downloading it as a dependency to your project.

https://github.com/trycoon/Adafruit_ADXL345

Thanks!

**Comment by ivankravets** [comment]
Thanks, done! http://platformio.org/lib/show/1756/Adafruit%20ADXL345%20fork
