### ISSUE TITLE
Add/Update FixedPoints Lib

### ISSUE THREAD

**Issue by yinkou** [platformio/platformio-libmirror#106]
Hello,

The library [FixedPoints](https://github.com/Pharap/FixedPointsArduino) has been updated to v1.0.2 but platformio hasn't updated it yet.
I've talked with the maintainer and he said that he hasn't even ever added the lib to platformio which makes me wonder how it's already listed.
We created a library.json file and i ask to (re)add it to your libraries or somehow trigger the update.

`pio lib register` keeps telling me that it's an _"Invalid URL or broken manifest. Please validate it with http://jsonlint.com"_ but i have checked it a couple of times and it's fine as far as i can tell. Probably it's the https?

Now we don't know what to do so I'm here and asking.

Thank you!

**Comment by ivankravets** [comment]
We check for new updates/releases 1 time per 24 hours.

http://platformio.org/lib/show/1882/FixedPoints
