### ISSUE TITLE
Hornbill-AWS_IOT

### ISSUE THREAD

**Issue by kemaldede** [platformio/platformio-libmirror#111]
Please add this library supporting aws-iot for the arduino-esp32 
Thank you 
https://github.com/ExploreEmbedded/Hornbill-Examples/tree/master/arduino-esp32/AWS_IOT

**Comment by ivankravets** [comment]
Done! http://platformio.org/lib/show/2071/AWS_IOT

**Comment by kemaldede** [comment]
Thank you:) You'r doing a great job

2018-01-06 17:14 GMT+03:00 Ivan Kravets <notifications@github.com>:
