### ISSUE TITLE
Please add OSC arduino library

### ISSUE THREAD

**Issue by jottr** [platformio/platformio-libmirror#13]
As the title says, please add the following library to platformio:

https://github.com/CNMAT/OSC

**Comment by ivankravets** [comment]
Thanks, done!:

* https://github.com/CNMAT/OSC/pull/30
* http://platformio.org/#!/lib/show/423/OSC

**Comment by jottr** [comment]
That was lightning fast! Thank you @ivankravets.

**Comment by ivankravets** [comment]
Tips! You can also add library to PlatformIO Library Registry. See here http://docs.platformio.org/en/latest/librarymanager/creating.html
