### ISSUE TITLE
update ros_lib library

### ISSUE THREAD

**Issue by bochen87** [platformio/platformio-libmirror#136]
Hi, I requested to add a library and it was added, thanks a lot!

I've realized that one file was wrong and corrected that in the git repository - can you please update that also in the library that one get's from platformio library manager? It's currently still with the wrong file.

https://platformio.org/lib/show/5526/ros_lib%20Arduino

**Comment by ivankravets** [comment]
New version in manifest will trigger crawler

**Comment by bochen87** [comment]
@ivankravets i updated the manifest this morning, but nothing seemed to happen - or is the crawler rather a nightly batch process?
