### ISSUE TITLE
TinyHead

### ISSUE THREAD

**Issue by Thijxx** [platformio/platformio-libmirror#144]
I've created a library for Radiohead on the ATTiny85
https://gitlab.com/thijsvanulden/TinyHead

**Comment by ivankravets** [comment]
Could you create manifest for this library and make PR? See https://docs.platformio.org/en/latest/librarymanager/creating.html

**Comment by Thijxx** [comment]
I'm sorry, I should have read that before. Now I added the `library.json` and I used `platformio lib register https://gitlab.com/thijsvanulden/TinyHead/raw/master/library.json` to register it. It is awaiting moderation. Thanks!

**Comment by ivankravets** [comment]
Done! https://platformio.org/lib/show/6014/TinyHead

Thanks!
