### ISSUE TITLE
please add ESPArto library

### ISSUE THREAD

**Issue by HamzaHajeir** [platformio/platformio-libmirror#146]
Hi

Can you please add ESPArto library and its parent libraries ?
https://github.com/philbowles/esparto#you-will-then-need-to-install-the-following-third-party-libraries

H4 is only added at PlatformIO.

If not possible, How to add external libraries to a project (not registered to your data).

Thanks

**Comment by ivankravets** [comment]
Done! See recently added libraries https://platformio.org/lib

**Comment by HamzaHajeir** [comment]
Thanks a lot :)
