### ISSUE TITLE
Add a new lib

### ISSUE THREAD

**Issue by zjd0112** [platformio/platformio-libmirror#150]
I want to register a new library on PlatformIO, but when I run 
**`platformio lib register XXX/library.json`**, 
it show me an error:  **"Invalid URL or broken manifest."**. 
I have checked it a couple of times, and I have not found any errors on "library.json".
My lib repo is https://github.com/TinyLink/TinyLink_Library_Arduino
Now I don't know how to register my lib correctly
Thank you!

**Comment by legenddcr** [comment]
It registered successfully now.
