### ISSUE TITLE
LiquidCrystal_AIP31068

### ISSUE THREAD

**Issue by red-scorp** [platformio/platformio-libmirror#168]
Please add:
https://github.com/red-scorp/LiquidCrystal_AIP31068

**Comment by ivankravets** [comment]
Please register with https://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#cmd-lib-register

**Comment by ivankravets** [comment]
Please register with https://docs.platformio.org/en/latest/userguide/lib/cmd_register.html#cmd-lib-register
