### ISSUE TITLE
Add SwiCago/HeatPump for Mitsubishi Heatpump control over serial line

### ISSUE THREAD

**Issue by geoffdavis** [platformio/platformio-libmirror#171]
https://github.com/SwiCago/HeatPump contains an Arduino library with support for Mitsubishi heat pumps.

Arduino library.properties is here: https://github.com/SwiCago/HeatPump/blob/master/library.properties

**Comment by ivankravets** [comment]
Done! https://platformio.org/lib/show/7096/HeatPump
