### ISSUE TITLE
RadioHead 1.101

### ISSUE THREAD

**Issue by renatoconstanciofilho** [platformio/platformio-libmirror#174]
Please update the RadioHead to 1.101 library.
Site: https://www.airspayce.com/mikem/arduino/RadioHead/
Files: http://www.airspayce.com/mikem/arduino/RadioHead/RadioHead-1.101.zip

**Comment by ivankravets** [comment]
Thanks! Resolved in https://github.com/platformio/platformio-libmirror/commit/43d5e5ea5985fb95abe6222eff0ccb7e99dd7cf3
