### ISSUE TITLE
Add rhio-LIS2HH12 library

### ISSUE THREAD

**Issue by JoseMartiRhombio** [platformio/platformio-libmirror#179]
Hello,

rhomb.io have developed a LIS2HH12 library to run this accelerometer
Could you add the https://gitlab.com/rhombio/rhio-libraries/rhio-LIS2HH12 to PlatformIO?

**Comment by JoseMartiRhombio** [comment]
I'm edited the url

**Comment by ivankravets** [comment]
Thanks, done! https://platformio.org/lib/show/7506/rhio-LIS2HH12

**Comment by JoseMartiRhombio** [comment]
@ivankravets I've changed the version to v0.1.1 for the url change
