### ISSUE TITLE
add Arduino-Scheduler lib

### ISSUE THREAD

**Issue by roener** [platformio/platformio-libmirror#181]
Hi,

would like to see Arduino-Scheduler added.
https://raw.githubusercontent.com/mikaelpatel/Arduino-Scheduler/master/library.properties

Tried `platformio lib register https://raw.githubusercontent.com/mikaelpatel/Arduino-Scheduler/master/library.properties` but only got `Error: [API] Method Not Allowed`

**Comment by ivankravets** [comment]
Hi,

The library is added https://platformio.org/lib/show/8229/Simple%20Scheduler

The bug is fixed. Thanks for the report!
