### ISSUE TITLE
library repo url moved (crawler doesn't follow redirects)

### ISSUE THREAD

**Issue by owennewo** [platformio/platformio-libmirror#188]
I help maintain the `Simple FOC` library.  

This lib has moved to a new URL:
from: https://github.com/askuric/Arduino-FOC
to:     https://github.com/simplefoc/Arduino-FOC

Arduino IDE is happy with the redirect but platformio crawler only has old version details.

Can you do one of the following:
- update the url for this lib 
- or get crawler to follow the redirects

If neither are possible, would asking arduino to update their library info mean that the url you have will fix itself next time your crawler crawls?

Thankyou!

**Comment by ivankravets** [comment]
Thanks, fixed in https://platformio.org/lib/show/7229/Simple%20FOC
