### ISSUE TITLE
Please provide the stable 1.5 version of MySensors.org

### ISSUE THREAD

**Issue by wollew** [platformio/platformio-libmirror#19]
The currently provided library version of Mysensors (ID 548) seems to be the bleeding edge developer version, I'd much prefer to have the stable 1.5 release. Maybe as an alternative at least.

**Comment by ivankravets** [comment]
I've just made PR https://github.com/mysensors/Arduino/pull/365

Also, this issue depends on https://github.com/platformio/platformio-api/issues/18 and https://github.com/platformio/platformio-api/issues/19

**Comment by ivankravets** [comment]
Done http://platformio.org/#!/lib/show/548/MySensors

**Comment by wollew** [comment]
That was fast, thank you.
