### ISSUE TITLE
Requesting addition of LibLightModbus

### ISSUE THREAD

**Issue by ControlSystemIntegrators** [platformio/platformio-libmirror#192]
LibLightModbus is a pure C, hardware agnostic, complete implementation of the Modbus Protocol, supporting both RTU and TCP.

https://jacajack.github.io/liblightmodbus/

**Comment by ivankravets** [comment]
Please forward to https://github.com/Jacajack/liblightmodbus/issues and refer to this URL https://docs.platformio.org/en/latest/librarymanager/creating.html
