### ISSUE TITLE
Please add hx711 library

### ISSUE THREAD

**Issue by SirUli** [platformio/platformio-libmirror#23]
Hello,

could you add the hx711 library to the platformio libraries? https://github.com/bogde/HX711

Thanks in advance!

Best Regards,
Uli

**Comment by SirUli** [comment]
I created a pull request over there: https://github.com/bogde/HX711/pull/27

**Comment by ivankravets** [comment]
Thanks a lot! Done http://platformio.org/#!/lib/show/1100/HX711

**Comment by SirUli** [comment]
Now that was fast - thanks @ivankravets !

**Comment by ivankravets** [comment]
We have an issue for that https://github.com/platformio/platformio-atom-ide/issues/45 and will fix it in the new version of PlatformIO IDE.
