### ISSUE TITLE
mbed TextLCD library

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-libmirror#24]
please add following TextLCD library:
https://developer.mbed.org/users/wim/code/TextLCD/
It is an extended library for LCD Panels and have much more features than
the library from simon ford.

**Comment by ivankravets** [comment]
Could you make PR to https://github.com/platformio/platformio-libmirror/tree/master/configs/mbed ?

See examples:
* https://github.com/platformio/platformio-libmirror/blob/master/configs/mbed/TextLCD_DaveVanWagner.json
* https://github.com/platformio/platformio-libmirror/blob/master/configs/mbed/TextLCD_SimonFord.json
