### ISSUE TITLE
Please add Adafruit HDC1000

### ISSUE THREAD

**Issue by Damoun** [platformio/platformio-libmirror#26]
Hello,

Could you add this library : https://github.com/adafruit/Adafruit_HDC1000_Library

Thank you

**Comment by ivankravets** [comment]
Done!

* http://platformio.org/#!/lib/show/1102/Adafruit-HDC1000
* https://github.com/platformio/platformio-libmirror/blob/master/configs/adafruit/arduino-hdc1000.json
