### ISSUE TITLE
Add Bounce2

### ISSUE THREAD

**Issue by marvinroger** [platformio/platformio-libmirror#28]
Please add [Bounce2](https://github.com/thomasfredericks/Bounce2) to the registry as I think a lot of people are using it as a dependency. Thanks! :)

**Comment by ivankravets** [comment]
Done!

* https://github.com/thomasfredericks/Bounce2/pull/22
* http://platformio.org/#!/lib/show/1106/Bounce2

**Comment by marvinroger** [comment]
Great! Thanks a lot.
