### ISSUE TITLE
Can you add Nextion display library?

### ISSUE THREAD

**Issue by alonewolfx2** [platformio/platformio-libmirror#29]
Can you add Nextion display library?

**Comment by ivankravets** [comment]
Please provide repo

**Comment by alonewolfx2** [comment]
https://github.com/itead/ITEADLIB_Arduino_Nextion

**Comment by ivankravets** [comment]
Done!

https://github.com/itead/ITEADLIB_Arduino_Nextion/pull/10

**Comment by alonewolfx2** [comment]
Thx
