### ISSUE TITLE
MMA8452Q Accelerometer Library

### ISSUE THREAD

**Issue by evgorchakov** [platformio/platformio-libmirror#32]
Would very much like to see this accelerometer library added:
https://github.com/sparkfun/SparkFun_MMA8452Q_Arduino_Library/

**Comment by valeros** [comment]
Done! https://github.com/sparkfun/SparkFun_MMA8452Q_Arduino_Library/pull/3

**Comment by evgorchakov** [comment]
That was quick, thank you!
