### ISSUE TITLE
Teleinfo

### ISSUE THREAD

**Issue by nlamirault** [platformio/platformio-libmirror#38]
Hi,
could you please add [Teleinfo][] to the registry.
Thanks.

[Teleinfo]: https://github.com/hallard/LibTeleinfo

**Comment by ivankravets** [comment]
@nlamirault please merge https://github.com/hallard/LibTeleinfo/pull/7/commits/b991b2560d7ebfd0f8e634a7fd475625718c4f04

**Comment by ivankravets** [comment]
Thanks! Done http://platformio.org/lib/show/214/LibTeleinfo
