### ISSUE TITLE
Support for Mighty Boards 

### ISSUE THREAD

**Issue by peekpt** [platformio/platformio-libmirror#40]
For ATmega1284, ATmega644, ATmega324, ATmega164, ATmega32, ATmega16 and ATmega8535
I found this boards on github , seems to be update regularly and with good documentation. 
https://github.com/MCUdude/MightyCore
Please consider to add this bunch of boards from Mighty to your database, since the support for ATmega644/1284 from other boards are like sanguino, microduino are not updated anymore.

Thank you!

**Comment by valeros** [comment]
Hi @peekpt 
Please open this issue in the corresponding [repository](https://github.com/platformio/platformio/issues).
