### ISSUE TITLE
Add Libraries rc-switch, VirtualWire

### ISSUE THREAD

**Issue by TheOneValen** [platformio/platformio-libmirror#45]
Hi!

I am proposing the following libraries for the repository:

https://www.pjrc.com/teensy/td_libs_VirtualWire.html
https://github.com/sui77/rc-switch

Greetings.

**Comment by valeros** [comment]
Done!
http://platformio.org/lib/show/251/VirtualWire
http://platformio.org/lib/show/246/RCSwitch

**Comment by TheOneValen** [comment]
Wow that was fast. To imagine what time I could have saved with platformio compared to fiddling with Makefiles...

There is a newer version available for VirtualWire (Final one)
http://www.airspayce.com/mikem/arduino/VirtualWire/VirtualWire-1.27.zip

Which is the only lib I would need to fully migrate to platformio and ditch my makefiles...
