### ISSUE TITLE
Please add DimSwitch library

### ISSUE THREAD

**Issue by krzychb** [platformio/platformio-libmirror#50]
Hi PlaformIO Team,

Please add [DimSwitch](https://github.com/krzychb/DimSwitch) library. 
It has been developed to control dimmable ballasts for fluorescent light tubes.

I have just started with PlatformIO IDE. Within couple of hours got confident with it by importing, compiling and uploading various `ino` code. I have tested this particular library in `lib` directory _intended for the project specific (private) libraries_. Now would like to check how it will work out of Library Manager. 

The Atom editor together with all the magic PlatofrmIO code under the hood works nice, quick and stable:+1: 

Congratulations on developing great ecosystem! :smile:

Krzysztof

**Comment by valeros** [comment]
Added http://platformio.org/lib/show/270/DimSwitch
Thanks!
