### ISSUE TITLE
Firmata library

### ISSUE THREAD

**Issue by mgcrea** [platformio/platformio-libmirror#57]
Would be great to add https://github.com/firmata/arduino.

Thanks!

**Comment by valeros** [comment]
Added http://platformio.org/lib/show/307/Firmata

Please keep in mind that by default PlatformIO builder does not search library dependencies in `utility` directory, so if you have next error `fatal error: SoftwareSerial.h: No such file or directory` just 
include "SoftwareSerial.h" to your sketch or enable [library dependency finder](http://docs.platformio.org/en/latest/projectconf.html#lib-dfcyclic) in `platformio.ini`
PS: Some frameworks contain default `Firmata` library as well.
