### ISSUE TITLE
Add rene-mt/esp8266-oled-sh1106

### ISSUE THREAD

**Issue by SirUli** [platformio/platformio-libmirror#61]
Hello,

could you please add https://github.com/rene-mt/esp8266-oled-sh1106?

Thanks in advance!

Best Regards,
Uli

**Comment by ivankravets** [comment]
Hi,

Need to wait when @rene-mt will merge this  PR https://github.com/rene-mt/esp8266-oled-sh1106/pull/1.

Thanks.

**Comment by SirUli** [comment]
Thanks! I totally overlooked the URL - only checked if the library.json is there already. Thanks for spotting!

**Comment by rene-mt** [comment]
Merged, thanks for the fix, I also overlooked it :)

**Comment by ivankravets** [comment]
Thanks! http://platformio.org/lib/show/312/SH1106

**Comment by SirUli** [comment]
Thanks a lot!
