### ISSUE TITLE
NTPClient (551) has moved?

### ISSUE THREAD

**Issue by SirUli** [platformio/platformio-libmirror#62]
Hello,

It looks as if http://platformio.org/lib/show/551/NTPClient has moved to https://github.com/arduino-libraries/NTPClient

It became evident when downloading the library 551 which does not contain the same functions and behaves not according to the examples (e.g. getEpochTime() is missing).

As the Link https://github.com/FWeinb/NTPClient.git points to https://github.com/arduino-libraries/NTPClient i'd assume that it has been moved there?

Best Regards,
Uli

**Comment by ivankravets** [comment]
Thanks! Let's wait when @FWeinb merge PR https://github.com/arduino-libraries/NTPClient/pull/18 .

**Comment by ivankravets** [comment]
Updated http://platformio.org/lib/show/551/NTPClient

**Comment by SirUli** [comment]
Thank you!!!
