### ISSUE TITLE
Add updated MAX6675 Library

### ISSUE THREAD

**Issue by SirUli** [platformio/platformio-libmirror#66]
As Adafruit is not updating the MAX6675 library (http://platformio.org/lib/show/558/Adafruit-MAX6675) anymore i forked the library and updated it with all outstanding pull requests as well as additional changes (like the recommended directory structure and Travis CI Integration)

Wanted to ask if you'd be willing to add the fork?

https://github.com/SirUli/MAX6675

**Comment by valeros** [comment]
Added http://platformio.org/lib/show/343/MAX6675
Thanks!

**Comment by SirUli** [comment]
Awesome - thank you!!!
