### ISSUE TITLE
Include ConfigurableFirmata

### ISSUE THREAD

**Issue by SirUli** [platformio/platformio-libmirror#69]
Hello,

could you please include the ConfigurableFirmata as Library as well?

Link: https://github.com/firmata/ConfigurableFirmata

THANKS!

Best Regards,
Uli

**Comment by valeros** [comment]
Added http://platformio.org/lib/show/363/ConfigurableFirmata
Thanks!

**Comment by SirUli** [comment]
Thank you - awesome!
