### ISSUE TITLE
Add support for TinyWireM and TinyWire RTClib

### ISSUE THREAD

**Issue by stonehippo** [platformio/platformio-libmirror#82]
Please add support for the Adafruit TinyWireM and TinyWireM-compatible RTClib libraries:

https://github.com/adafruit/TinyWireM
https://github.com/adafruit/TinyRTCLib

**Comment by ivankravets** [comment]
* http://platformio.org/lib/show/797/TinyWireM
* http://platformio.org/lib/show/685/TinyRTCLib
