### ISSUE TITLE
Add support for Adafruit Bluetooth Module Firmata

### ISSUE THREAD

**Issue by stonehippo** [platformio/platformio-libmirror#83]
Please add support for Adafruit BLE module Firmata:

https://github.com/adafruit/Adafruit_BLE_PinIO

**Comment by ivankravets** [comment]
You can register library using [platformio lib register](http://docs.platformio.org/en/stable/userguide/lib/cmd_register.html) command where need to pass RAW url to `arduino.properties` file.

http://platformio.org/lib/show/848/Adafruit%20BLEFirmata
