### ISSUE TITLE
Add Adafruit SI1145 Library

### ISSUE THREAD

**Issue by mhaas** [platformio/platformio-libmirror#84]
https://github.com/adafruit/Adafruit_SI1145_Library

Thanks! :)

**Comment by ivankravets** [comment]
You can register library using [platformio lib register](http://docs.platformio.org/en/stable/userguide/lib/cmd_register.html) command where need to pass RAW url to `arduino.properties` file.

http://platformio.org/lib/show/496/Adafruit%20SI1145%20Library
