### ISSUE TITLE
arduinoVNC for ESP8266

### ISSUE THREAD

**Issue by Links2004** [platformio/platformio-libmirror#94]
feel free to add my arduinoVNC Client library to the repo.

https://github.com/Links2004/arduinoVNC

**Comment by ivankravets** [comment]
Which manifest to use? You have PlatformIO & Arduino. We support both. What is more, you can submit library manually
- http://docs.platformio.org/en/stable/userguide/lib/cmd_register.html

P.S: If you decide to use PlatformIO `library.json`, please add `version` field. PlatformIO 3.0 has been released with powerful Library Manager with SemVer support.

**Comment by Links2004** [comment]
ok, thanks for the info will do this.
