### ISSUE TITLE
OpenCM support?

### ISSUE THREAD

**Issue by vblagomir** [platformio/platformio-libmirror#98]
Would be great if Platformio could support OpenCM cards, the official controller card for Dynamixel motors: http://www.robotis.us/opencm9-04-c-with-onboard-xl-type-connectors/

Their IDE is unusable, whereas the motors are the best servos available. Platformio could be a perfect IDE for it.

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-ststm32/issues
